require 'rake'
require 'rspec/core/rake_task'

desc 'Default: Run all specs for Rails 3.'
task :default => :spec

desc "Run all specs for Rails 3"
RSpec::Core::RakeTask.new(:spec) do |t|
  t.pattern = '**/*_spec.rb'
end