source 'http://rubygems.org'

# gem 'rails', '3.0.4'
# gem 'logical_tabs', :path => '../../..'
# gem 'haml'
# gem 'sqlite3-ruby', :require => 'sqlite3'
#
# group :test do
#   gem "webrat"
#   gem "rspec", ">= 2.5.0"
#   gem "rspec-rails", ">= 2.5.0"
#   gem 'ruby-debug'
# end
